//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllGroupsInfo
    {
        public int GroupId { get; set; }
        public string GroupAuthority { get; set; }
        public string GroupSid { get; set; }
        public string GroupName { get; set; }
        public string GroupSamAccountName { get; set; }
        public string GroupObjectClass { get; set; }
        public string GroupDisplayName { get; set; }
        public string GroupDescription { get; set; }
        public string GroupDistinguishedName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Scope { get; set; }
        public bool IsBusy { get; set; }
        public bool IsVisited { get; set; }
        public bool IsExpanded { get; set; }
        public bool IsFaulty { get; set; }
        public int MemberId { get; set; }
        public string MemberObjectClass { get; set; }
        public string MemberAuthority { get; set; }
        public string MemberSid { get; set; }
        public string MemberName { get; set; }
        public string MemberSamAccountName { get; set; }
        public string MemberDisplayName { get; set; }
        public string MemberDescription { get; set; }
        public string MemberDistinguishedName { get; set; }
        public string ISDIRECT { get; set; }
    }
}
