//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_ASSOC
    {
        public string ServerFqdn { get; set; }
        public string ServerSID { get; set; }
        public int Id { get; set; }
        public string Ext { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string Authority { get; set; }
    }
}
