//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public string Authority { get; set; }
        public string Sid { get; set; }
        public string Name { get; set; }
        public string SamAccountName { get; set; }
        public string ObjectClass { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string DistinguishedName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Scope { get; set; }
        public bool IsBusy { get; set; }
        public bool IsVisited { get; set; }
        public bool IsExpanded { get; set; }
        public bool IsFaulty { get; set; }
    }
}
