//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_INFO
    {
        public int ID { get; set; }
        public string ServerFqdn { get; set; }
        public string ServerSID { get; set; }
        public string ServerGUID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Authority { get; set; }
        public string DomainNetbiosName { get; set; }
        public string SamAccountName { get; set; }
    }
}
