//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_Principals
    {
        public System.Guid ID { get; set; }
        public Nullable<int> GID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string SID { get; set; }
        public Nullable<int> TrusteeID { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.Guid> ParentPrincipalID { get; set; }
        public Nullable<bool> IsDirectSiteAdmin { get; set; }
    }
}
