//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPN
    {
        public Nullable<bool> Enabled { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastPasswordSet { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public bool PasswordNeverExpires { get; set; }
        public bool UserCannotChangePassword { get; set; }
        public string ExchMasterAccountSid { get; set; }
        public string UPN { get; set; }
        public Nullable<int> UAC { get; set; }
        public Nullable<System.DateTime> BadPasswordTime { get; set; }
        public Nullable<System.DateTime> AccountExpires { get; set; }
        public string AllowedToDelegateTo { get; set; }
        public Nullable<int> KeyVersionNumber { get; set; }
        public int Expr1 { get; set; }
        public string Authority { get; set; }
        public string Sid { get; set; }
        public string Name { get; set; }
        public string SamAccountName { get; set; }
        public string ObjectClass { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string DistinguishedName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
        public Nullable<System.DateTime> WhenChanged { get; set; }
        public string SPN1 { get; set; }
    }
}
