//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlDatabas
    {
        public int Id { get; set; }
        public int SqlInstanceId { get; set; }
        public string Name { get; set; }
        public byte[] OwnerSqlSid { get; set; }
        public Nullable<int> OwnerTrusteeId { get; set; }
        public string State { get; set; }
        public string CollationName { get; set; }
        public string RecoveryMode { get; set; }
    }
}
