//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ALL_DRIVERS
    {
        public int Id { get; set; }
        public string ModuleName { get; set; }
        public string DisplayName { get; set; }
        public string DriverType { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
