//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AZURE_DIRECTORY_ROLES
    {
        public string TenantName { get; set; }
        public string Role { get; set; }
        public string Info { get; set; }
        public string RoleMemberTpe { get; set; }
        public string ObjectSid { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int ID { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
