//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CA_MANAGER_RIGHTS
    {
        public string Officer { get; set; }
        public string Users { get; set; }
        public string ACEType { get; set; }
        public string Template { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public int ID { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
