//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIAGNOSTICS
    {
        public int Id { get; set; }
        public System.Guid OpId { get; set; }
        public string OpName { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> N1 { get; set; }
        public Nullable<int> N2 { get; set; }
        public Nullable<int> N3 { get; set; }
        public Nullable<int> N4 { get; set; }
        public Nullable<int> N5 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
        public string OpStep { get; set; }
        public Nullable<int> N6 { get; set; }
        public Nullable<int> N7 { get; set; }
        public Nullable<int> N8 { get; set; }
        public Nullable<int> N9 { get; set; }
        public Nullable<int> N10 { get; set; }
        public string S6 { get; set; }
        public string S7 { get; set; }
        public string S8 { get; set; }
        public string S9 { get; set; }
        public string S10 { get; set; }
    }
}
