//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EVENT_4663_LOG
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public string SubjectUserSid { get; set; }
        public string SubjectUserName { get; set; }
        public string SubjectDomainName { get; set; }
        public string SubjectLogonId { get; set; }
        public string ObjectServer { get; set; }
        public string ObjectType { get; set; }
        public string ObjectName { get; set; }
        public string HandleId { get; set; }
        public string AccessList { get; set; }
        public string AccessMask { get; set; }
        public string ProcessId { get; set; }
        public string ProcessName { get; set; }
        public string ResourceAttributes { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ServerId { get; set; }
    }
}
