//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KRBTGT_ATTRIBUTES
    {
        public int Id { get; set; }
        public string SID { get; set; }
        public string Authority { get; set; }
        public string msDS_KrbTgtLinkBl { get; set; }
    }
}
