//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOC_FIREWALL_RULES
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string RuleName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Direction { get; set; }
        public string Profiles { get; set; }
        public string Grouping { get; set; }
        public string LocalIP { get; set; }
        public string RemoteIP { get; set; }
        public string Protocol { get; set; }
        public string LocalPort { get; set; }
        public string RemotePort { get; set; }
        public Nullable<bool> EdgeTraversal { get; set; }
        public string Program { get; set; }
        public string Service { get; set; }
        public string InterfaceTypes { get; set; }
        public string Security { get; set; }
        public string RuleSource { get; set; }
        public string Action { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
