//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RODC_DATA
    {
        public int Id { get; set; }
        public string SID { get; set; }
        public string ManagedBy { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    }
}
