//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SID_HISTORY
    {
        public string ObjectSID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Info { get; set; }
        public string ObjectDN { get; set; }
        public string SIDHistory { get; set; }
        public int ID { get; set; }
        public Nullable<int> ServerID { get; set; }
        public string SIDHistorySamAccountName { get; set; }
        public string SIDHistoryDN { get; set; }
        public Nullable<bool> IsSameDomain { get; set; }
        public Nullable<bool> IsWellKnownSID { get; set; }
        public string WellKnownAccount { get; set; }
    }
}
