//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SIGNED_DRIVERS
    {
        public int Id { get; set; }
        public string DeviceName { get; set; }
        public string InfName { get; set; }
        public Nullable<bool> IsSigned { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
