//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRUSTS
    {
        public int Id { get; set; }
        public string ForestName { get; set; }
        public string DomainName { get; set; }
        public string TrustName { get; set; }
        public string TrustPartner { get; set; }
        public string TrustType { get; set; }
        public string TrustDirection { get; set; }
        public string TrustAttributes { get; set; }
        public string SupportedEncryptionTypes { get; set; }
        public string TrustSID { get; set; }
        public string RecordType { get; set; }
        public string DNSName { get; set; }
        public string NetBIOS { get; set; }
        public string SID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> ServerID { get; set; }
    }
}
