//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrusteesAsGroup
    {
        public int Id { get; set; }
        public string Scope { get; set; }
        public bool IsBusy { get; set; }
        public bool IsVisited { get; set; }
        public bool IsExpanded { get; set; }
        public bool IsFaulty { get; set; }
    }
}
