//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrusteesAsComputer
    {
        public int Id { get; set; }
        public string ComputerType { get; set; }
        public string OS { get; set; }
        public string OSServicePack { get; set; }
        public string OSVersion { get; set; }
    }
}
