//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACLXrayWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNRESOLVED_MEMBERSHIP
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string GroupDN { get; set; }
        public Nullable<bool> Resolved { get; set; }
    }
}
